name: 'push-to-cdn'

on:
  push:
    branches:
      - 'main'
      - 'dev-*'

jobs:
  dev-cdn:
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: 'actions/checkout@v3'
      - uses: 'actions/setup-node@v3'
        with:
          node-version: '16'
          cache: 'npm'
      - name: 'Install dependencies'
        run: 'npm ci'
      - name: 'Build application'
        run: 'npm run build'

      - id: upload
        uses: nais/frontend-plattform-cdn-upload-action@main
        with:
          cdn-environment: cdn.dev.nav.no
          cdn-team-name: min-side
          cache-invalidation: true
          source: ./dist/tms-min-side-varslinger.js
          destination: ''  # uploads folder to team root

      - run: echo uploaded file ${{ steps.upload.outputs.uploaded }}
        shell: bash

  prod-cdn:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: 'actions/checkout@v3'
      - uses: 'actions/setup-node@v3'
        with:
          node-version: '16'
          cache: 'npm'
      - name: 'Install dependencies'
        run: 'npm ci'
      - name: 'Build application'
        run: 'npm run build'

      - id: upload
        uses: nais/frontend-plattform-cdn-upload-action@main
        with:
          cdn-environment: cdn.nav.no
          cdn-team-name: min-side
          cache-invalidation: true
          source: ./dist/tms-min-side-varslinger.js
          destination: ''  # uploads folder to team root

      - run: echo uploaded file ${{ steps.upload.outputs.uploaded }}
        shell: bash
